### ISSUE TITLE
'rm: cannot remove (...): Directory not empty' error?

### ISSUE THREAD

**Issue by GeoMicroSoares** [Arkadiy-Garber/FeGenie#3]
Hi there,

Just installed FeGenie (again congrats on the tool!) via conda and tried running it on my bins as such: ```FeGenie.py -bin_dir Gal_FeGenie/ -bin_ext fa -t 16 -out Gal_FeGenie_out```.

Although in the end of the pipeline I do get the expected output files, as it runs I keep getting errors for all phases of the it past finding ORFs as such:

```
checking arguments
.
.
.
All required arguments provided!

Finding ORFs for Bin_24_1_1-contigs.fa
Finding ORFs for Bin_24_5_1-contigs.fa
Finding ORFs for Bin_28_2-contigs.fa
Finding ORFs for Bin_50_3-contigs.fa
Finding ORFs for Bin_56_3-contigs.fa
Finding ORFs for Bin_56_4-contigs.fa
Finding ORFs for Bin_56_6-contigs.fa
Finding ORFs for Bin_56_7_1-contigs.fa
Finding ORFs for Bin_56_8-contigs.fa
starting main pipeline...

.
Looking for following iron-related functional category: iron_aquisition-heme_oxygenase
analyzing Bin_24_1_1-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_24_1_1-contigs.fa-HMM’: Directory not empty
analyzing Bin_24_5_1-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_24_5_1-contigs.fa-HMM’: Directory not empty
analyzing Bin_28_2-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_28_2-contigs.fa-HMM’: Directory not empty
analyzing Bin_50_3-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_50_3-contigs.fa-HMM’: Directory not empty
analyzing Bin_56_3-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_56_3-contigs.fa-HMM’: Directory not empty
analyzing Bin_56_4-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_56_4-contigs.fa-HMM’: Directory not empty
analyzing Bin_56_6-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_56_6-contigs.fa-HMM’: Directory not empty
analyzing Bin_56_7_1-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_56_7_1-contigs.fa-HMM’: Directory not empty
analyzing Bin_56_8-contigs.fa: 100%   
rm: cannot remove ‘Gal_FeGenie///Bin_56_8-contigs.fa-HMM’: Directory not empty
```
Any ideas? Can't be sure if the pipeline ran that well with all this...

Thanks in advance :)

**Comment by Arkadiy-Garber** [comment]
Hey André,

Thanks for the note on this! Those 'rm' error messages should have no effect on the final output. So feel free to move forward with the output files worry-free :)

I've been aware of this issue, and currently trying to find a remedy. I believe that these sorts of errors stem from some kind of underlying permissions issue, since my beta-testers only reported this when FeGenie was run on shared computing clusters. I just updated FeGenie's script to use 'rmdir' instead of 'rm', and will have it tested on several servers soon.

The good news is that this has absolutely no effect on the final output files.

Cheers, and hope you find this program useful!
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Hey André,

Thanks for the note on this! Those 'rm' error messages should have no effect on the final output. So feel free to move forward with the output files worry-free :)

I've been aware of this issue, and currently trying to find a remedy. I believe that these sorts of errors stem from some kind of underlying permissions issue, since my beta-testers only reported this when FeGenie was run on shared computing clusters. I just updated FeGenie's script to use 'rmdir' instead of 'rm', and will have it tested on several servers soon.

The good news is that this has absolutely no effect on the final output files.

Cheers, and hope you find this program useful!
Arkadiy

**Comment by Arkadiy-Garber** [comment]
This issue has been resolved in the latest version. Feel free to do a fresh git clone and try it out!
