### ISSUE TITLE
Why the FeGenie installed by conda and the FeGenie installed manually work very differently？

### ISSUE THREAD

**Issue by xdli009** [Arkadiy-Garber/FeGenie#31]
Hi,

Thanks for the tool. Since I found that the annotations obtained from FeGenie installed by conda were few. I test the FeGenie installed by conda and the FeGenie installed manually. The results of these two approaches are very different. Why?

Thank you!

**Comment by xdli009** [comment]
Yes,FeGenie manually mean installation-if-you-don't-have-conda.

I ran the test data(Rhodopseudomonas_palustris_TIE-1.txt-proteins.faa) and the results were also different.

Command:
`FeGenie.py -bin_dir ./ -bin_ext faa -out fegenie_out_conda --orfs -t 36`

Results:


> Hi, thanks for your interest in FeGenie! Sorry that you are having issues. When you installed FeGenie manually, do you mean that you followed this installation protocol: https://github.com/Arkadiy-Garber/FeGenie#installation-if-you-dont-have-conda?
> 
> Any chance you can share the output files from the two runs?
> 
> Thanks, Arkadiy

**Comment by xdli009** [comment]
@Arkadiy-Garber 

Hi Arkadiy, what are the reasons of the above problems? Which way should I install the software?

Thanks!

**Comment by Arkadiy-Garber** [comment]
Hi,

Apologies for the delay in getting this issue resolved. I believe the discrepancy is caused by the fact that the FeGenie package that is available via conda is an outdated version. So the results from the manual install should be used. For what it's worth, I just tagged a new FeGenie version release, so the conda recipe for FeGenie should be updated with the latest updates and bug fixes within a few days. Please use the manual install if you want to go with the results you already have. Otherwise, please wait a few days and try again with a conda install.

Let me know if you have any questions about this, continue to see differences in the results, or run into any other issues. Again, apologies for this confusion, and for the delay in getting this issue resolved.

Thanks,
Arkadiy

**Comment by xdli009** [comment]
@Arkadiy-Garber

Hi Arkadiy, I have the same problem as Chao. @ChaoLab  

When I open the HMM result from FeGenie, I find that "MtoA.hmm.tblout"  reports some hits. But "FeGenie-geneSummary.csv"  reports no hits about MtoA.  I am confused on what cutoff values and/or other criteria manual-installed FeGeine really uses?

Thanks!

**Comment by Arkadiy-Garber** [comment]
Hi,

Apologies for the confusion about this. The reason why you see some hits reported in the tblout from hmmsearch, but not in the main summary output, is because in addition to the bit score cutoffs for each individual HMM, FeGenie uses a gene cluster/operon detecting algorithm to filter out potential false positive hits. For example, in the case of MtoA, there may be some protein sequences that surpass the bit score threshold set in FeGenie (and these hits would be reported in "MtoA.hmm.tblout". However, in order to be reported as potential iron oxidation/reduction, this gene would need to be found encoded next to a porin like MtrB. If that is not present, then it is likely that the protein identified by the MtoA HMM is not really involved in iron reduction or oxidation. Does this make sense?

You have the option of setting the following flag in the FeGenie command: --all_results. If you do that, FeGenie will generate a summary file that features all HMM matches, regardless of operon or gene neighborhood structure.

Hope that helps to relieve some of the confusion. Let me know if there are additional questions or issues.

Thanks,
Arkadiy

**Comment by xdli009** [comment]
Thank you very much for your reply!

**Comment by iordanistheocharis-lgtm** [comment]
@Arkadiy-Garber 

Hi Arkadiy,

First of all, thank you for developing FeGenie.

I am a new user, and I am a bit confused about the installation process. I apologize if I have misunderstood something.

From the installation guide, I first followed the Conda/Mamba instructions:

mamba create -n fegenie \
  -c conda-forge -c bioconda \
  ...
conda activate fegenie

echo ${CONDA_PREFIX}
mkdir -p ${CONDA_PREFIX}/etc/conda/activate.d
echo '#!/bin/sh
export PATH="'$(pwd)':$PATH"
export rscripts="'$(pwd)'/rscripts"
export iron_hmms="'$(pwd)'/hmms/iron"' > ${CONDA_PREFIX}/etc/conda/activate.d/env_vars.sh

I also confirmed that:

echo ${iron_hmms}

returned the correct path.

However, when I tried:

FeGenie.py -h

I received:

command not found

Because of that, I assumed that I also needed to perform the manual installation, so I followed these steps:

git clone https://github.com/Arkadiy-Garber/FeGenie.git
cd FeGenie
bash setup.sh
./FeGenie.py -h

After doing this, FeGenie.py -h worked correctly.

My question is: is this the expected installation procedure?

Do I need both the Conda/Mamba installation and the manual installation, or have I misunderstood the documentation and accidentally performed two different installations?

Sorry if this is a very basic question—I just want to make sure I am using FeGenie correctly before analyzing my data.

Thank you very much for your time.

Best regards,
Iordanis
